options:
  service_name:
    default: ScriptInjection
    name: Service name
    notes: Service name note 
  exec_command:
    default: ps aux | grep apache
    name: Command for execution 
    notes: Command for execution note
 
metadata:
  value:
    unit: /min
    precision: 2